DNA = 'ATACGTAGAGCAAGGACGTCGAACAGTCATGAAAGTCTTAGTACCGCACGTACCATCTTACTGAGAATATTGCCTGAAGCTGTACCGTTATAGGGGGGCAAAGATGAAGATCTCCTCTTTTCATAACTGTACTCGCGAGGGCCGTGTTGCCGGTTTCTTCAGAGGTTAAAGAATAAAGGCTTACTGTACGCAGAGGAACGCCCATTTAGTGGCTGGCGTTATGAATCTTCGGACCCCCTTGTCTATCCAGATTAATCGAATTCTCTCATTTAGGACCCTAGTAAGTCATCATTGGTATATGAATGCGACCCCGAAGAAGCCGCCTAAAAATGACAGTGGTTGGTCCTCTAAACTTCATTTGGTTAACTCGTGTATCGGCGCGATAGGCCGTTAGAGGTTTAATATTGTATGGCAAGGTACTTCCGGTCTTAATGAATGGCCGGGAAAGGTACGCACGCGGTATGGGGGGGTGAGGGGGCGAATAGGCAGGCTCGCCTCTGTCACGCTAGGAGGCAATTCTATAAGAATGCACACTGCATCGATACATAAAACGTCTCGATCGCTTGCGCAACTTGTGAAGTGTCTACCATCCCTAAGCCCATTTCCCGCATATTAACCCCTGATTGTATCCGCATCTGATGCTACCGTGGTTGAGTTAGCGTCGAGCACGCGGGACTTATTGCATGAGTAGAGTTGACTAAGAGCCGTTAGATGGCTCGCTGAGCTAATAGTTGCCGACAGATCGTCAAGATTAGAAAACGGTTGTAGCATTATCGGAGGTTCTCTAACTAGTATCGATAGCCGTGTCTTCACTGTGCCGCGGCTACCTATCGCCTGAAAACCAGTTGGTGTTAAGGGGTCCCCTGTCCAGGACGCCACGCGTAGTGAGACATACACGTTCGTTGGGTTCACCCGGGTCGGACCTGAGTCGACCAAGGACACACTCGAGCTCCGACCCCTACTGTCGAGAAATTTGTATCCCGCCCCCGCAGCTTGCCAG'

print("Ilosc GC w wygenerowanym DNA: ",DNA.count("GC"))


An = DNA.count('A')
Tn = DNA.count('T')
Cn = DNA.count('C')
Gn = DNA.count('G')

MW = (An * 313.2) + (Tn * 304.2) + (Cn * 289.2) + (Gn * 329.2) + 79.0
print('Masa czasteczkowa wynosi: ')
print(MW)


def translacja(DNA):
    triplety = {'ATA': 'I', 'ATC': 'I', 'ATT': 'I', 'ATG': 'M',
               'ACA': 'T', 'ACC': 'T', 'ACG': 'T', 'ACT': 'T',
               'AAC': 'N', 'AAT': 'N', 'AAA': 'K', 'AAG': 'K',
               'AGC': 'S', 'AGT': 'S', 'AGA': 'R', 'AGG': 'R',
               'CTA': 'L', 'CTC': 'L', 'CTG': 'L', 'CTT': 'L',
               'CCA': 'P', 'CCC': 'P', 'CCG': 'P', 'CCT': 'P',
               'CAC': 'H', 'CAT': 'H', 'CAA': 'Q', 'CAG': 'Q',
               'CGA': 'R', 'CGC': 'R', 'CGG': 'R', 'CGT': 'R',
               'GTA': 'V', 'GTC': 'V', 'GTG': 'V', 'GTT': 'V',
               'GCA': 'A', 'GCC': 'A', 'GCG': 'A', 'GCT': 'A',
               'GAC': 'D', 'GAT': 'D', 'GAA': 'E', 'GAG': 'E',
               'GGA': 'G', 'GGC': 'G', 'GGG': 'G', 'GGT': 'G',
               'TCA': 'S', 'TCC': 'S', 'TCG': 'S', 'TCT': 'S',
               'TTC': 'F', 'TTT': 'F', 'TTA': 'L', 'TTG': 'L',
               'TAC': 'Y', 'TAT': 'Y', 'TAA': '_', 'TAG': '_',
               'TGC': 'C', 'TGT': 'C', 'TGA': '_', 'TGG': 'W', }

    bialka = ''
    for i in range(0, len(DNA) -len(DNA)%3, 3):
            kodon = DNA[i:i+3]
            bialka += triplety[kodon]
    return bialka
print(translacja(DNA))



    

